language: go
go:
  - 1.9.x
  - 1.8.x
  - 1.7.x
env:
  matrix:
    - ONIG_VERSION=6.1.3
addons:
  apt:
    packages:
      - make
      - build-essential
      - gcc-4.8
      - g++-4.8
      - libtool
install:
  - make onigmo
script:
  - make ci
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
