language: go
sudo: required
go:
  - 1.11.x
  - 1.10.x
  - 1.9.x
  - 1.8.x
  - 1.7.x
  - master
env:
  - ONIG_VERSION=6.1.3 GO111MODULE=on CGO_LDFLAGS=/usr/local/lib/libonigmo.a
addons:
  apt:
    packages:
      - make
      - build-essential
      - gcc-4.8
      - g++-4.8
      - libtool
install:
  - make onigmo
script:
  - make test
  - make order
    on:
      go: 1.11.x
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
